//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Task3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supermarket
    {
        public Supermarket()
        {
            this.SalesReports = new HashSet<SalesReport>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<SalesReport> SalesReports { get; set; }
    }
}
