//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SagittaDB.Models.MySQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class expens
    {
        public int id { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public int vendor_id { get; set; }
        public Nullable<decimal> sum { get; set; }
    
        public virtual vendor vendor { get; set; }
    }
}
