//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SagittaDB.Models.MySQL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class sagittadb_mysqlEntities : DbContext
    {
        public sagittadb_mysqlEntities()
            : base("name=sagittadb_mysqlEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<expens> expenses { get; set; }
        public virtual DbSet<product> products { get; set; }
        public virtual DbSet<vendor> vendors { get; set; }
    }
}
